<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="$(JetBrainsRiderSdkReference)" Condition="Exists('$(JetBrainsRiderSdkReference)')" />

    <PropertyGroup>
        <TargetFramework>net472</TargetFramework>
        <AssemblyName>ReSharperPlugin.MvvmPlugin</AssemblyName>
        <RootNamespace>$(AssemblyName)</RootNamespace>
        <IsPackable>false</IsPackable>
        <DefineConstants>$(DefineConstants);RIDER</DefineConstants>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Update="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" />
    </ItemGroup>

</Project>
